blank_issues_enabled: false
contact_links:
  - name: QuickCode 7 Documentation
    url: https://github.com/elementaryrock/quickcode7#readme
    about: Check out the documentation for more information about QuickCode 7
