name: Project Submission
description: Submit your project for the Hackathon
title: "[Project Submission]: "
labels: ["project-submission"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # Hackathon Project Submission
        Thank you for participating! Please fill out the information below to submit your project.

  - type: input
    id: name
    attributes:
      label: Full Name
      description: Your full name
      placeholder: "e.g., John Doe"
    validations:
      required: true

  - type: input
    id: project_name
    attributes:
      label: Project Name
      description: The name of your project
      placeholder: "e.g., Weather App"
    validations:
      required: true

  - type: input
    id: repository_url
    attributes:
      label: GitHub Repository URL
      description: Link to your GitHub repository (must be public)
      placeholder: "https://github.com/username/repository"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Project Description
      description: A brief description of your project (50-100 words)
      placeholder: "Describe what your project does, what technologies you used, and why you created it."
    validations:
      required: true

  - type: textarea
    id: team_members
    attributes:
      label: Team Members
      description: If this is a team project, list all team members with their roles
      placeholder: |
        1. John Doe - Frontend Developer
        2. Jane Smith - Backend Developer
        3. ...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this project, you agree to follow our code of conduct
      options:
        - label: I confirm that this project is my original work and adheres to the Hackathon guidelines
          required: true
        - label: I understand my submission will be evaluated based on code quality, functionality, and innovation
          required: true

  - type: markdown
    attributes:
      value: |
        ## What's Next?
        After submitting this form, a maintainer will review your submission and add it to the repo.
        You will receive feedback and next steps via comments on this issue.
